project_id = "ypgoodjdxcnjysrsortp"

[functions.super-task]
verify_jwt = false

[functions.send-phone-otp]
verify_jwt = false

[functions.verify-phone-otp]
verify_jwt = false

[functions.create-building-report]
verify_jwt = false
