project_id = "ypgoodjdxcnjysrsortp"

[functions.super-task]
verify_jwt = false

[functions.send-phone-otp]
verify_jwt = false

[functions.verify-phone-otp]
verify_jwt = false

[functions.building-at-risk]
verify_jwt = false
