project_id = "ypgoodjdxcnjysrsortp"

[functions.building-at-risk]
verify_jwt = false

[functions.quick-endpoint]
verify_jwt = false

[functions.classify-report]
verify_jwt = false

[functions.create-issue]
verify_jwt = false

[functions.dismiss-issue]
# Validates JWT in code for flexibility
verify_jwt = false
